spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zps
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQL10Dialect
      database: postgresql
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

server:
  servlet:
    session:
      timeout: 5m
  port: 8080
  tomcat:
    accesslog:
      enabled: true
    directory: logs
    file-date-format: yyyy-mm-dd
    prefix: access_log
    suffix: .log
